import './globals.css'
import { Inter } from 'next/font/google'
import Header from './header/Header'
import Footer from './footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shopping app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
